sudo: false

language: node_js
node_js:
  - 10
services:
- mongodb

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "task-chat-ap"
  api_key:
    secure: "4d4666ff-4965-422e-8427-9a76a3e08680"